version: '3.3'

services:
  postgres:
      image: postgres:15
      restart: always
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
      ports:
        - '5432:5432'
      volumes:
        - ./data:/var/lib/postgresql/data